name: ci-node-workflow
on: [push]
jobs: 
  check-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm ci
      - run: npx jest
      - run: npm start